### ISSUE TITLE
Cross compiling with i686-apple-darwin10

### ISSUE THREAD

**Issue by zamaudio** [falkTX/DPF#1]
Tried compiling zam-plugins-DPF with

CC=i686-apple-darwin10-gcc CXX=i686-apple-darwin10-g++ CFLAGS=-m32 CXXFLAGS=-m32 make MACOS=true

Got:
i686-apple-darwin10-g++ ZamCompArtwork.cpp.o ZamCompUI.cpp.o ../../libs/distrho/DistrhoUIMain.cpp ../../libs/libdgl.a -Wall -Wextra -pipe -fPIC -DPIC -DNDEBUG -O2 -ffast-math -mtune=generic -msse -msse2 -mfpmath=sse -fdata-sections -ffunction-sections -fvisibility=hidden -m32 -fvisibility-inlines-hidden -I. -I../../libs/distrho -I../../libs/dgl -fdata-sections -ffunction-sections -Wl,-dead_strip -Wl,-dead_strip_dylibs  -framework OpenGL -framework Cocoa -I/opt/kxstudio/include  -L/opt/kxstudio/lib -llo -lpthread -lm   -DDISTRHO_PLUGIN_TARGET_DSSI -o ../../bin/ZamComp-dssi/ZamComp_ui
In file included from ../../libs/distrho/DistrhoUIMain.cpp:22:
../../libs/distrho/src/DistrhoUIDSSI.cpp:48: error: integer constant is too large for 'long' type
../../libs/distrho/src/DistrhoUIDSSI.cpp:48: error: integer constant is too large for 'long' type
../../libs/distrho/src/DistrhoUIDSSI.cpp:56: error: integer constant is too large for 'long' type
../../libs/distrho/src/DistrhoUIDSSI.cpp:56: error: integer constant is too large for 'long' type
../../libs/distrho/src/DistrhoUIDSSI.cpp:64: error: integer constant is too large for 'long' type
../../libs/distrho/src/DistrhoUIDSSI.cpp:64: error: integer constant is too large for 'long' type
../../libs/distrho/src/DistrhoUIDSSI.cpp:72: error: integer constant is too large for 'long' type
../../libs/distrho/src/DistrhoUIDSSI.cpp:72: error: integer constant is too large for 'long' type
../../libs/distrho/src/DistrhoUIDSSI.cpp:80: error: integer constant is too large for 'long' type
../../libs/distrho/src/DistrhoUIDSSI.cpp:80: error: integer constant is too large for 'long' type
../../libs/distrho/src/DistrhoUIDSSI.cpp:243: warning: unused parameter 'path'
make[1]: **\* [../../bin/ZamComp-dssi/ZamComp_ui] Error 1
make[1]: Leaving directory `/home/damien/git/audio/zam-plugins-DPF/plugins/ZamComp'
make: **\* [plugins] Error 2

**Comment by zamaudio** [comment]
I have liblo-static installed from kxstudio

**Comment by falkTX** [comment]
All those errors coincide with lo_send stuff.
You probably have something not yet configured 100%.
